import { GeminiClient } from './geminiClient';
import { PersonaMode } from '../types';

export interface CodeGenerationResult {
  language: string;
  code: string;
  explanation: string;
  complexity: string;
  runnableInApp: boolean;
}

export class CodeGenerator {
  public static async generateCode(
    prompt: string,
    language: string = 'javascript',
    mode: PersonaMode = 'JARVIS',
    apiKey: string = ''
  ): Promise<CodeGenerationResult> {
    const lang = language.toLowerCase().trim();

    if (apiKey && apiKey.trim().length > 5) {
      try {
        const systemPrompt = `You are an expert software engineer and code generator operating in ${mode} mode.
Write clean, well-structured, production-ready ${language} code for the following request:
"${prompt}"

Return your response in valid JSON with this exact structure:
{
  "code": "the full code implementation",
  "explanation": "concise technical breakdown of how the code works",
  "complexity": "Time and space complexity (e.g., O(N) time, O(1) space)"
}`;

        const res = await GeminiClient.generateResponse(systemPrompt, [], mode, apiKey);
        if (res) {
          try {
            const cleanJson = res.replace(/```json/g, '').replace(/```/g, '').trim();
            const parsed = JSON.parse(cleanJson);
            return {
              language: lang,
              code: parsed.code || res,
              explanation: parsed.explanation || 'Code generated according to specifications.',
              complexity: parsed.complexity || 'Varies based on input size',
              runnableInApp: lang === 'javascript' || lang === 'js',
            };
          } catch (e) {
            return {
              language: lang,
              code: res,
              explanation: 'Generated by language model.',
              complexity: 'N/A',
              runnableInApp: lang === 'javascript' || lang === 'js',
            };
          }
        }
      } catch (e) {
        console.warn('Code generator model error:', e);
      }
    }

    // High-fidelity fallback templates for offline / zero-key usage
    return this.getStandardTemplate(prompt, lang);
  }

  private static getStandardTemplate(prompt: string, language: string): CodeGenerationResult {
    const p = prompt.toLowerCase();

    if (language === 'python' || language === 'py') {
      if (p.includes('api') || p.includes('fetch') || p.includes('http')) {
        return {
          language: 'python',
          code: `import requests
import json

def fetch_data(endpoint: str, timeout: int = 10) -> dict:
    """Fetches and parses JSON payload from a REST endpoint."""
    try:
        response = requests.get(endpoint, timeout=timeout)
        response.raise_for_status()
        return response.json()
    except requests.RequestException as err:
        print(f"[ERROR] Request failed: {err}")
        return {}

if __name__ == "__main__":
    url = "https://api.github.com/events"
    result = fetch_data(url)
    print(f"Retrieved {len(result)} records.")`,
          explanation: 'Uses the requests library with robust timeout and exception handling to query endpoints.',
          complexity: 'Time: O(N) network payload processing, Space: O(N) response buffer',
          runnableInApp: false,
        };
      }

      return {
        language: 'python',
        code: `def solve_problem(data: list[int]) -> dict:
    """Processes numerical sequence and returns statistical metrics."""
    if not data:
        return {"count": 0, "sum": 0, "average": 0.0}
    
    total = sum(data)
    average = total / len(data)
    sorted_data = sorted(data)
    median = sorted_data[len(data) // 2]
    
    return {
        "count": len(data),
        "sum": total,
        "average": round(average, 2),
        "median": median
    }

if __name__ == "__main__":
    sample = [42, 19, 88, 3, 91, 56, 77]
    metrics = solve_problem(sample)
    print("Computed Metrics:", metrics)`,
        explanation: 'Performs statistical computation, aggregate calculation, and sequence analysis.',
        complexity: 'Time: O(N log N) due to sorting, Space: O(N)',
        runnableInApp: false,
      };
    }

    if (language === 'typescript' || language === 'ts') {
      return {
        language: 'typescript',
        code: `interface TaskRecord {
  id: string;
  title: string;
  completed: boolean;
  priority: 'low' | 'medium' | 'high';
  createdAt: number;
}

class TaskManager {
  private tasks: Map<string, TaskRecord> = new Map();

  public addTask(title: string, priority: TaskRecord['priority'] = 'medium'): TaskRecord {
    const task: TaskRecord = {
      id: \`task_\${Date.now()}_\${Math.random().toString(36).substring(2, 7)}\`,
      title,
      completed: false,
      priority,
      createdAt: Date.now(),
    };
    this.tasks.set(task.id, task);
    return task;
  }

  public completeTask(id: string): boolean {
    const task = this.tasks.get(id);
    if (!task) return false;
    task.completed = true;
    return true;
  }

  public getPendingTasks(): TaskRecord[] {
    return Array.from(this.tasks.values()).filter((t) => !t.completed);
  }
}

export const taskManager = new TaskManager();`,
        explanation: 'Implements a typed in-memory task registry with Map indexing and CRUD operations.',
        complexity: 'Time: O(1) for insert/update, O(N) for filtered query. Space: O(N)',
        runnableInApp: false,
      };
    }

    if (language === 'sql') {
      return {
        language: 'sql',
        code: `-- Schema and analytics query
CREATE TABLE IF NOT EXISTS system_logs (
    id SERIAL PRIMARY KEY,
    module_name VARCHAR(64) NOT NULL,
    threat_level VARCHAR(16) DEFAULT 'NOMINAL',
    latency_ms INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexing for fast range queries
CREATE INDEX idx_logs_created ON system_logs(created_at DESC);

-- Aggregate performance metrics
SELECT 
    module_name,
    COUNT(*) AS total_executions,
    ROUND(AVG(latency_ms), 2) AS avg_latency_ms,
    MAX(latency_ms) AS peak_latency_ms
FROM system_logs
WHERE created_at >= NOW() - INTERVAL '24 HOURS'
GROUP BY module_name
ORDER BY avg_latency_ms DESC;`,
        explanation: 'Creates a relational log schema with timestamp indices and calculates aggregate latency statistics.',
        complexity: 'Time: O(N) index scan, Space: O(N) log storage',
        runnableInApp: false,
      };
    }

    // Default JavaScript (Executable in mobile app)
    return {
      language: 'javascript',
      code: `// Dynamic Algorithm Execution Sandbox
function calculateFibonacciPrimes(limit = 20) {
  const isPrime = (num) => {
    if (num <= 1) return false;
    for (let i = 2; i <= Math.sqrt(num); i++) {
      if (num % i === 0) return false;
    }
    return true;
  };

  const fib = [0, 1];
  while (fib.length < limit) {
    fib.push(fib[fib.length - 1] + fib[fib.length - 2]);
  }

  const primes = fib.filter(isPrime);
  return {
    fibonacciSequence: fib,
    primeFibonacciNumbers: primes,
    totalPrimesFound: primes.length
  };
}

console.log("Executing Fibonacci Prime Analysis...");
const result = calculateFibonacciPrimes(15);
console.log("Fibonacci:", result.fibonacciSequence.join(", "));
console.log("Primes:", result.primeFibonacciNumbers.join(", "));
return result;`,
      explanation: 'Generates Fibonacci numbers and filters for prime occurrences using square-root factor checking.',
      complexity: 'Time: O(N * sqrt(M)) where M is the magnitude of the largest term. Space: O(N)',
      runnableInApp: true,
    };
  }
}
